project.version=4.0.0-beta-5
server.paper=io.papermc.paper:paper-api:1.21.11-R0.1-SNAPSHOT
server.bungeecord=net.md-5:bungeecord-api:1.21-R0.1-SNAPSHOT
server.velocity=com.velocitypowered:velocity-api:3.3.0-SNAPSHOT
libs.lombok=org.projectlombok:lombok:1.18.30
libs.adventure_api=net.kyori:adventure-api:4.25.0
libs.adventure_bom=net.kyori:adventure-bom:4.25.0
libs.adventure_text_minimessage=net.kyori:adventure-text-minimessage:4.25.0
libs.adventure_text_serializer_gson=net.kyori:adventure-text-serializer-gson:4.25.0
libs.adventure_text_serializer_legacy=net.kyori:adventure-text-serializer-legacy:4.25.0
libs.adventure_text_serializer_plain=net.kyori:adventure-text-serializer-plain:4.25.0
libs.cc_yaml=cn.chengzhimeow:CC-Yaml:2.1.23
libs.cc_action=cn.chengzhimeow:CC-Action:2.0.23
libs.cc_condition=cn.chengzhimeow:CC-Condition:2.0.22
libs.cc_scheduler=cn.chengzhimeow:CC-Scheduler:2.0.4
libs.mhdf_library=cn.chengzhiya:MHDF-Library:1.0.3
libs.mhdf_database_api=cn.chengzhiya:MHDF-Database-API:1.0.3
libs.mhdf_database_mysql=cn.chengzhiya:MHDF-Database-MySQL:1.0.3
libs.mhdf_database_h2=cn.chengzhiya:MHDF-Database-H2:1.0.3
libs.log4j_core=org.apache.logging.log4j:log4j-core:2.24.3
libs.fastjson=com.alibaba.fastjson2:fastjson2:2.0.57
libs.reflections=org.reflections:reflections:0.10.2
libs.lettuce=io.lettuce:lettuce-core:6.5.5.RELEASE
libs.nyana_cache=net.nyana:nyana-cache:1.0.2
libs.nyana_cache_hashmap=net.nyana:nyana-cache-hashmap:1.0.2
libs.nyana_cache_redis=net.nyana:nyana-cache-redis:1.0.2
libs.nyana_message=net.nyana:nyana-message:1.0.1
libs.nyana_nbt_tag=net.nyana:nyana-nbt-tag:1.0.0
libs.nyana_nbt_codec=net.nyana:nyana-nbt-codec:1.0.0
libs.nyana_reflection=net.nyana:nyana-reflection:1.0.2
libs.exp4j=net.objecthunter:exp4j:0.4.8
libs.packetevents=com.github.retrooper:packetevents-spigot:2.10.1
plugin.placeholderapi=me.clip:placeholderapi:2.11.6
plugin.mythicmobs=io.lumine:Mythic-Dist:5.9.5
plugin.vault=com.github.MilkBowl:VaultAPI:1.7.1
plugin.craftengine_core=net.momirealms:craft-engine-core:0.0.65
plugin.craftengine_bukkit=net.momirealms:craft-engine-bukkit:0.0.65
