name: maven package - v3

on:
  push:
    branches: [ "v3" ]
  pull_request:
    branches: [ "v3" ]

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    environment: default
    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'
      - name: Build projects
        run: mvn package
      - name: Upload Artifact
        uses: "actions/upload-artifact@v4"
        with:
          name: "MHDF-Tools Artifacts"
          path: "build/*.jar"